# docker-compose.yml
version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./extractions:/app/extractions  # Mount volume for extracted videos
    environment:
      - PYTHONUNBUFFERED=1
    # Add specific system resources for video processing
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
